[project]
name = "llm-benchmark-shram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.34.2",
    "pandas>=2.3.1",
    "vllm>=0.10.0",
]
